// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juygmbdrwfgpkrrattjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eWdtYmRyd2ZncGtycmF0dGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTg2MTQsImV4cCI6MjA2MTk3NDYxNH0.p-s0ujNZgwlk_jElHsXyNfLAC0wA5oXPzmdiNY8a2BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);